version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        Version: ${Version}
    image: api_online:${tag}
    container_name: blog_api_online
    restart: always
    # env_file: .env
    environment:
      - DB_USER=$DB_USER
      - DB_PASS=$DB_PASS
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - DB_NAME=$DB_NAME
      - BASE_URL=$BASE_URL
      - PORT=$PORT
    ports:
      - "${PORT}:4000"
    volumes:
      - /home/html/public:/app/public

networks:
  default:
    external:
      name: https
